// remote-react/src/components/Counter.tsx
import '../index.css';

import { ReactNode, useState } from 'react';

export default function Counter(): ReactNode {
    const [count, setCount] = useState(0);

    return (
        <div>
            <button className="border border-white py-1 px-2" onClick={() => setCount((count) => count + 1)}>
                Clicked {count} times.
            </button>
        </div>
    )
}

// remote-vue/src/components/Counter/Counter.vue
<script setup lang="ts">
import {ref} from 'vue';
import {CounterProps} from './types';

defineProps<CounterProps>();

const count = ref(0);

function increment() {
    count.value++;
}
</script>

<template>
    <button class="border border-green-300 px-1 py-2" :title="tooltip" @click="increment">
        Clicked Vue {{ count }} times.
    </button>
</template>
